version: "2.1"

services:
  rem213-postgres:
    image: postgres:12.4
    container_name: cancercompanion
    mem_limit: 50m
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "cancer-companion"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - local-bridge

networks:
  local-bridge: # default network
    driver: bridge
