spring:
  application:
    name: cancercompanion
  datasource:
    url: jdbc:postgresql://localhost:5432/cancer-companion
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: ${SECRET_TOKEN}
    expire-after-minutes: 120

tomze:
  youtube-client:
    access-token: ${YOUTUBE_TOKEN}